postgres:
  host: postgres
  port: 5432
  user: ml_user
  password: ml_pass
  db: ml_db
mlflow:
  uri: http://mlflow:5000
training:
  target_col: load_kwh
  features:
    - lag_1
    - lag_24
    - hour
    - dayofweek
    - month
  test_size: 0.2
  random_state: 42
